### ISSUE TITLE
Android - video doesn't play on touch - Chrome + Firefox 

### ISSUE THREAD

**Issue by staus** [molamil-com/codethewave-framework#2]
Samsung S6 - Android
Both chrome and Firefox used to work
1. I refresh the page
2. there's a call to play() which fails
3. i touch the screen
4. there's 2 more calls to play which also fails

I think this error message is important.
`Handling of 'touchmove' input event was delayed for 230 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.`

If the event was delayed it might not be considered a user interaction anymore which makes the play() call fail. The user interaction has to call play() instantly.

<img width="693" alt="screen shot 2016-10-06 at 15 50 00" src="https://cloud.githubusercontent.com/assets/7048437/19154952/d32eaea4-8bdc-11e6-8972-dd2f9cc63b98.png">

**Comment by staus** [comment]
UPDATE
I just tried to play an example hosted on molamil.com ([VideoMasking](http://scarletpleasure.molamil.com/examples/VideoMasking.html))
Video still doesn't play.
Audio plays automatically.

I get a bit different error message. Is this one something we should be aware of?
`Performing operations that require explicit user interaction on touchstart events is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5649871251963904 for more details.`

<img width="697" alt="screen shot 2016-10-06 at 16 00 56" src="https://cloud.githubusercontent.com/assets/7048437/19155330/46e73978-8bde-11e6-91ff-a88270ed52ac.png">

**Comment by respada** [comment]
I've just deployed an fix for this on 0.016.
