### ISSUE TITLE
Android - video / videomask seems scaled - Chrome

### ISSUE THREAD

**Issue by staus** [molamil-com/codethewave-framework#3]
I start the experience [WebAudioAnalyser](http://scarletpleasure.molamil.com/examples/WebAudioAnalyser.html) and see this. I tap play and the experience begin

![screenshot_20161007-144330](https://cloud.githubusercontent.com/assets/7048437/19190393/918c6510-8c9d-11e6-8273-05bf44489494.png)

Most of the time I see _no_ video, but occasionally something like this pops in

![screenshot_20161007-144955](https://cloud.githubusercontent.com/assets/7048437/19190418/b0a17e18-8c9d-11e6-8156-8e1212918554.png)
As you can see the black around his hand isn't masked

It's definately running smoothly. I just suspect the scaling or position of the mask is off somehow. When I see some of the mask on the video it's also very blurry, so again, I think the videomask layer isn't scaled properly. The video layer itself could be ok scaled

**Comment by respada** [comment]
0.017 should fix this by forcing the resolution to be 1 or 2 but nothing else than those 2 alternatives.
